spring:
  profiles:
    active: dev
  data:
    redis:
      database: 1
      host: 172.16.2.10
      port: 6379
      timeout: 5000
      jedis:
        pool:
          max-active: 10
      password: c1$4T&9pW#z2Q@7vL
